### ISSUE TITLE
 Issue resolved

### ISSUE THREAD

**Issue by LeSoFi2** [madve2/uppp-pixabay-for-office#3]

**Comment by madve2** [comment]
Normally I wouldn't react to such a harsh comment, but since accusations of spreading malware are serious, even if completely baseless, now I feel like I have to. I know you have deleted your comment by now, so you probably have figured it out yourself, but I still kind of have an obligation to alleviate concerns, in case someone saw it in the meantime, or got an e-mail notification about it like I did.

First of all, this plugin does not contain malware. It is open source, you can check yourself, and even build it yourself from source using the instructions provided if you don't trust the version in the Office store.

I don't use Office anymore, and as a result, the plugin is not really maintained, so bugs may have started appearing in it. That said, JavaScript-based Office plugins, like this one, are, by design, connected to your Microsoft account, and, for your _convenience_, are automatically reinstalled when you reinstall Office. This is not my decision, this is not malicious code in the plugin, this is a feature implemented by Microsoft that I can do nothing about, and as far as I know, it applies to all plugins using this technology. You have to remove the plugin from your Microsoft account.

It is a shame that some of the people that Microsoft support is employing don't even know how the software they are supporting works, and they so often resolve to suggest reinstalling everything (I also have similarly abysmal experiences with Microsoft support), but throwing grave accusations at innocent open source developers out of your frustration is really, really not OK.
